POST http://localhost:11500/api/account/login
Content-Type: application/json

{
    "PlayerID" : "test04",
    "AuthToken" : "94ILRSD4LRXE6N",
    "AppVersion" : "0.1",
    "MasterDataVersion" : "0.1"
}

###
POST http://localhost:11500/api/account/create
Content-Type: application/json

{
    "PlayerID" : "test04",
    "AuthToken" : "94ILRSD4LRXE6N",
    "AppVersion" : "0.1",
    "MasterDataVersion" : "0.1"
}

###
POST http://localhost:11500/api/account/defaultdata
Content-Type: application/json

{
    "UserID" : 96,
    "AuthToken" : "ficn87n56x09pxf1bihv3voo3",
    "AppVersion" : "0.1",
    "MasterDataVersion" : "0.1"
}