### 계정 생성 (클라이언트 최초 접속)
POST http://localhost:11500/api/auth/create
Content-Type: application/json

{
    "PlayerID" : "test04",
    "AuthToken" : "94ILRSD4LRXE6N",
    "AppVersion" : "0.1",
    "MasterDataVersion" : "0.1"
}

### 로그인
POST http://localhost:11500/api/auth/login
Content-Type: application/json

{
    "PlayerID" : "test04",
    "AuthToken" : "94ILRSD4LRXE6N",
    "AppVersion" : "0.1",
    "MasterDataVersion" : "0.1"
}

### 게임 기본 데이터 로드
POST http://localhost:11500/api/load/defaultdata
Content-Type: application/json

{
    "UserID" : 96,
    "AuthToken" : "ficn87n56x09pxf1bihv3voo3",
    "AppVersion" : "0.1",
    "MasterDataVersion" : "0.1"
}

### 로그아웃
POST http://localhost:11500/api/auth/logout
Content-Type: application/json

{
    "UserID" : 97,
    "AuthToken" : "qod72ydn5zl7u8cydxy0fc7wl",
    "AppVersion" : "0.1",
    "MasterDataVersion" : "0.1"
}

### 출석 체크
POST http://localhost:11500/api/attend
Content-Type: application/json

{
    "UserID" : 99,
    "AuthToken" : "8fzg1yu71r8g3u77mbe4rj7tv",
    "AppVersion" : "0.1",
    "MasterDataVersion" : "0.1"
}